---
- name: Update APT cache if Ubuntu / Debian
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "3600"

- name: Install Ubuntu / Debian pre-req software
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: latest
  loop: "{{ prereq_software }}"

- name: Download GPG keys for Docker for Ubuntu / Debian
  ansible.builtin.get_url:
    url: "{{ key_url }}"
    dest: "{{ key_dest }}"
    mode: "0644"

- name: Add repo for Ubuntu / Debian
  ansible.builtin.apt_repository:
    repo: "{{ repo }}"
    state: present

- name: Update APT cache if Ubuntu / Debian
  ansible.builtin.apt:
    update_cache: true
