---
# tasks file for docker-ce
- name: Load OS specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution_file_variety }}.yml"

- name: Run OS specific tasks
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution_file_variety }}.yml"

- name: Install Docker
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: latest
  loop: "{{ docker_software }}"
  notify:
    - Ensure that the Docker and Containerd services start on boot
    - Check if Docker and Containerd services are running
    - Check if Docker packages were installed
    - Evaluating raveshaww.docker_ce checks
