---
# tasks file for docker-ce
- name: Load OS specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution_file_variety }}.yml"

- name: Run OS specific tasks
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution_file_variety }}.yml"

- name: Install Docker
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: latest
  loop: "{{ docker_software }}"

- name: Ensure that the Docker and Containerd services start on boot
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: started
    enabled: true
  loop: "{{ services }}"

- name: Check if services are running
  ansible.builtin.service_facts:
  register: service_state

- name: Check if packages were installed
  ansible.builtin.package_facts:
  register: package_state

- name: Evaluating checks
  ansible.builtin.assert:
    that:
      - service_state.ansible_facts.services["containerd.service"].state == "running"
      - service_state.ansible_facts.services["docker.service"].state == "running"
      - package_state.ansible_facts.packages["docker-ce"] is defined
      - package_state.ansible_facts.packages["docker-ce-cli"] is defined
      - package_state.ansible_facts.packages["docker-buildx-plugin"] is defined
      - package_state.ansible_facts.packages["docker-compose-plugin"] is defined
    success_msg: "All checks passed"
